In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
#import numpy as np
#import dateutil

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
nyc_rental_load = "\\Users\\Paul-DS\\Downloads\\Neighborhood_Zri_AllHomesPlusMultifamily.csv"
nyc_rental_data=pd.read_csv(nyc_rental_load)
#nyc_mean_price_sales = "Resources/nyc_mean_price_per_sqft.csv"
#nyc_price_per_sqft = pd.read_csv(nyc_mean_price_sales)

In [2]:
bronx_rent = nyc_rental_data[nyc_rental_data["CountyName"]=="Bronx"]

In [3]:
bronx_region=[]
bronx_region = bronx_rent['RegionName'].unique()

In [4]:
bronx_region

array(['Williamsbridge', 'Soundview', 'South Bronx', 'Parkchester',
       'Wakefield', 'Morris Park', 'Melrose', 'Throggs Neck',
       'Kingsbridge', 'Pelham Gardens', 'Pelham Bay', 'Castle Hill',
       'Baychester', 'Spuyten Duyvil', 'Riverdale', 'North Riverdale',
       'Eastchester', 'Clason Point', 'Country Club', 'Woodlawn',
       'City Island'], dtype=object)

In [5]:
nyc_region_rent={}
for region in bronx_region:
    nyc_region_rent[region] = bronx_rent[nyc_rental_data["RegionName"]==region]
    nyc_region_rent[region] = nyc_region_rent[region].drop(columns=["RegionID","RegionName","City","State","Metro","SizeRank","CountyName"]).mean()
    nyc_region_rent[region] = pd.DataFrame(nyc_region_rent[region],columns=[region+' rental price'])

In [6]:
nyc_region_rent[region].index.rename('Date')

Index(['2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-07', '2011-08', '2011-09', '2011-10',
       '2011-11', '2011-12', '2012-01', '2012-02', '2012-03', '2012-04',
       '2012-05', '2012-06', '2012-07', '2012-08', '2012-09', '2012-10',
       '2012-11', '2012-12', '2013-01', '2013-02', '2013-03', '2013-04',
       '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10',
       '2013-11', '2013-12', '2014-01', '2014-02', '2014-03', '2014-04',
       '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10',
       '2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04',
       '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10',
       '2015-11', '2015-12', '2016-01', '2016-02', '2016-03', '2016-04',
       '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10',
       '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04',
       '2018-05', '2018-06', '2018-07'],
      dtype='object', name='Date')

In [7]:
#nyc_region_rent
for region in bronx_region:
    nyc_region_rent[region].index.rename('Date',inplace=True)
    #manhattan_region_df = manhattan_region_df.concat(nyc_region_rent[region])
    #manhattan_region_df = manhattan_region_df.join(nyc_region_rent[region])
#nyc_region_rent

In [8]:
first=0
for region in bronx_region:
    if first==0:
        df = pd.DataFrame(nyc_region_rent[region])
    else:
        df = df.join(pd.DataFrame(nyc_region_rent[region]))
    first=1

In [9]:
df

,Williamsbridge rental price,Soundview rental price,South Bronx rental price,Parkchester rental price,Wakefield rental price,Morris Park rental price,Melrose rental price,Throggs Neck rental price,Kingsbridge rental price,Pelham Gardens rental price,...,Castle Hill rental price,Baychester rental price,Spuyten Duyvil rental price,Riverdale rental price,North Riverdale rental price,Eastchester rental price,Clason Point rental price,Country Club rental price,Woodlawn rental price,City Island rental price
Date,,,,,,,,,,,,,,,,,,,,,
2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12,1537.0,1523.0,1554.0,1495.0,1539.0,1526.0,1564.0,1584.0,1530.0,1556.0,...,1552.0,1553.0,1644.0,1678.0,1646.0,1564.0,1552.0,1590.0,1514.0,1639.0
2012-01,1528.0,1513.0,1535.0,1490.0,1539.0,1515.0,1541.0,1574.0,1521.0,1538.0,...,1546.0,1533.0,1645.0,1663.0,1656.0,1562.0,1550.0,1572.0,1514.0,1624.0
2012-02,1521.0,1508.0,1523.0,1494.0,1539.0,1510.0,1530.0,1561.0,1511.0,1526.0,...,1535.0,1523.0,1637.0,1640.0,1657.0,1552.0,1546.0,1559.0,1515.0,1601.0
2012-03,1516.0,1505.0,1519.0,1506.0,1531.0,1506.0,1528.0,1549.0,1498.0,1517.0,...,1533.0,1519.0,1626.0,1614.0,1649.0,1532.0,1546.0,1543.0,1518.0,1576.0
2012-04,1520.0,1517.0,1533.0,1520.0,1543.0,1504.0,1536.0,1558.0,1497.0,1512.0,...,1549.0,1517.0,1619.0,1609.0,1660.0,1532.0,1559.0,1550.0,1533.0,1580.0
2012-05,1530.0,1532.0,1551.0,1548.0,1557.0,1509.0,1546.0,1575.0,1503.0,1509.0,...,1568.0,1512.0,1626.0,1620.0,1676.0,1532.0,1579.0,1564.0,1550.0,1590.0
2012-06,1539.0,1537.0,1572.0,1574.0,1576.0,1511.0,1568.0,1583.0,1525.0,1514.0,...,1582.0,1515.0,1651.0,1652.0,1695.0,1542.0,1601.0,1573.0,1573.0,1600.0
2012-07,1556.0,1545.0,1589.0,1603.0,1589.0,1529.0,1584.0,1587.0,1546.0,1529.0,...,1591.0,1534.0,1681.0,1689.0,1717.0,1552.0,1619.0,1576.0,1596.0,1610.0
2012-08,1579.0,1563.0,1609.0,1615.0,1613.0,1550.0,1607.0,1600.0,1573.0,1561.0,...,1610.0,1566.0,1716.0,1727.0,1751.0,1573.0,1641.0,1577.0,1628.0,1630.0
2012-09,1604.0,1594.0,1622.0,1616.0,1624.0,1573.0,1618.0,1616.0,1585.0,1578.0,...,1621.0,1585.0,1736.0,1750.0,1778.0,1589.0,1654.0,1585.0,1644.0,1647.0
2012-10,1611.0,1602.0,1613.0,1599.0,1624.0,1573.0,1618.0,1620.0,1588.0,1574.0,...,1620.0,1584.0,1737.0,1748.0,1780.0,1594.0,1652.0,1584.0,1645.0,1646.0
2012-11,1610.0,1601.0,1596.0,1580.0,1614.0,1568.0,1601.0,1613.0,1580.0,1563.0,...,1611.0,1576.0,1724.0,1731.0,1757.0,1595.0,1638.0,1583.0,1633.0,1637.0
2012-12,1606.0,1603.0,1584.0,1567.0,1608.0,1570.0,1592.0,1613.0,1576.0,1562.0,...,1611.0,1573.0,1721.0,1725.0,1730.0,1595.0,1627.0,1588.0,1620.0,1624.0
2013-01,1596.0,1603.0,1579.0,1557.0,1597.0,1581.0,1593.0,1618.0,1570.0,1576.0,...,1617.0,1577.0,1714.0,1720.0,1708.0,1588.0,1621.0,1598.0,1603.0,1617.0
2013-02,1585.0,1597.0,1584.0,1560.0,1588.0,1574.0,1607.0,1624.0,1566.0,1583.0,...,1616.0,1580.0,1701.0,1710.0,1686.0,1581.0,1614.0,1611.0,1583.0,1620.0
2013-03,1578.0,1590.0,1590.0,1564.0,1583.0,1564.0,1617.0,1621.0,1563.0,1576.0,...,1609.0,1578.0,1681.0,1700.0,1674.0,1576.0,1609.0,1616.0,1574.0,1625.0
2013-04,1584.0,1595.0,1607.0,1593.0,1586.0,1562.0,1628.0,1618.0,1571.0,1576.0,...,1606.0,1582.0,1688.0,1723.0,1684.0,1584.0,1609.0,1619.0,1580.0,1635.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-02,1829.0,1854.0,1860.0,1800.0,1866.0,1811.0,1836.0,1870.0,1811.0,1827.0,...,1836.0,1838.0,1977.0,2062.0,1975.0,1850.0,1869.0,1841.0,1851.0,1891.0
2016-03,1832.0,1855.0,1863.0,1812.0,1872.0,1816.0,1834.0,1866.0,1796.0,1827.0,...,1833.0,1840.0,1956.0,2028.0,1956.0,1861.0,1868.0,1843.0,1847.0,1880.0
2016-04,1825.0,1839.0,1850.0,1827.0,1875.0,1816.0,1824.0,1854.0,1774.0,1819.0,...,1823.0,1833.0,1947.0,1991.0,1923.0,1865.0,1850.0,1841.0,1840.0,1860.0
2016-05,1817.0,1819.0,1833.0,1834.0,1867.0,1815.0,1811.0,1842.0,1756.0,1821.0,...,1815.0,1828.0,1944.0,1974.0,1904.0,1861.0,1836.0,1839.0,1825.0,1850.0
2016-06,1805.0,1802.0,1818.0,1827.0,1847.0,1805.0,1802.0,1834.0,1749.0,1823.0,...,1803.0,1819.0,1962.0,1986.0,1907.0,1848.0,1821.0,1842.0,1808.0,1856.0
2016-07,1798.0,1795.0,1815.0,1815.0,1830.0,1794.0,1802.0,1835.0,1752.0,1824.0,...,1797.0,1816.0,1989.0,2022.0,1927.0,1839.0,1819.0,1849.0,1797.0,1876.0
2016-08,1791.0,1796.0,1823.0,1795.0,1828.0,1776.0,1814.0,1838.0,1754.0,1814.0,...,1796.0,1811.0,2025.0,2073.0,1959.0,1827.0,1824.0,1849.0,1793.0,1889.0
2016-09,1784.0,1803.0,1834.0,1774.0,1836.0,1761.0,1830.0,1841.0,1758.0,1803.0,...,1803.0,1809.0,2056.0,2125.0,1993.0,1820.0,1832.0,1844.0,1784.0,1897.0
2016-10,1770.0,1809.0,1839.0,1745.0,1837.0,1749.0,1844.0,1838.0,1759.0,1797.0,...,1807.0,1805.0,2080.0,2161.0,2020.0,1799.0,1835.0,1830.0,1769.0,1893.0
2016-11,1746.0,1803.0,1829.0,1709.0,1824.0,1739.0,1844.0,1823.0,1750.0,1782.0,...,1802.0,1789.0,2086.0,2179.0,2040.0,1771.0,1822.0,1812.0,1750.0,1879.0
2016-12,1720.0,1785.0,1817.0,1686.0,1799.0,1726.0,1840.0,1809.0,1739.0,1762.0,...,1784.0,1760.0,2077.0,2180.0,2053.0,1738.0,1805.0,1795.0,1734.0,1869.0
2017-01,1705.0,1768.0,1806.0,1677.0,1774.0,1714.0,1838.0,1801.0,1727.0,1746.0,...,1767.0,1736.0,2064.0,2175.0,2064.0,1721.0,1794.0,1793.0,1732.0,1872.0
2017-02,1707.0,1752.0,1797.0,1680.0,1765.0,1708.0,1835.0,1806.0,1723.0,1744.0,...,1751.0,1730.0,2056.0,2166.0,2061.0,1735.0,1788.0,1804.0,1746.0,1893.0
2017-03,1725.0,1748.0,1784.0,1660.0,1777.0,1717.0,1829.0,1819.0,1728.0,1752.0,...,1746.0,1746.0,2056.0,2158.0,2048.0,1772.0,1787.0,1824.0,1773.0,1913.0
2017-04,1741.0,1744.0,1772.0,1617.0,1789.0,1727.0,1822.0,1835.0,1737.0,1758.0,...,1746.0,1766.0,2050.0,2138.0,2026.0,1804.0,1790.0,1839.0,1788.0,1917.0
2017-05,1755.0,1752.0,1774.0,1575.0,1798.0,1737.0,1829.0,1855.0,1754.0,1763.0,...,1764.0,1785.0,2044.0,2116.0,2010.0,1825.0,1811.0,1843.0,1794.0,1917.0
2017-06,1766.0,1770.0,1793.0,1553.0,1803.0,1741.0,1852.0,1874.0,1771.0,1770.0,...,1787.0,1798.0,2056.0,2108.0,2012.0,1837.0,1845.0,1835.0,1795.0,1914.0
2017-07,1782.0,1793.0,1817.0,1541.0,1824.0,1742.0,1883.0,1889.0,1793.0,1779.0,...,1808.0,1807.0,2081.0,2123.0,2027.0,1857.0,1886.0,1820.0,1810.0,1925.0
2017-08,1804.0,1807.0,1838.0,1545.0,1857.0,1742.0,1900.0,1895.0,1808.0,1786.0,...,1814.0,1823.0,2106.0,2144.0,2054.0,1878.0,1917.0,1809.0,1832.0,1940.0
2017-09,1821.0,1809.0,1854.0,1561.0,1890.0,1741.0,1903.0,1895.0,1814.0,1786.0,...,1810.0,1834.0,2107.0,2157.0,2076.0,1891.0,1929.0,1802.0,1858.0,1962.0
2017-10,1834.0,1807.0,1870.0,1600.0,1909.0,1743.0,1907.0,1892.0,1818.0,1785.0,...,1803.0,1838.0,2090.0,2161.0,2087.0,1899.0,1924.0,1804.0,1875.0,1978.0
2017-11,1843.0,1811.0,1881.0,1634.0,1922.0,1759.0,1908.0,1888.0,1821.0,1787.0,...,1799.0,1836.0,2067.0,2154.0,2073.0,1909.0,1909.0,1816.0,1889.0,1999.0
2017-12,1853.0,1824.0,1890.0,1651.0,1933.0,1781.0,1914.0,1890.0,1825.0,1796.0,...,1805.0,1843.0,2048.0,2140.0,2048.0,1922.0,1897.0,1849.0,1898.0,2022.0
2018-01,1856.0,1835.0,1892.0,1641.0,1946.0,1801.0,1915.0,1900.0,1822.0,1807.0,...,1819.0,1852.0,2038.0,2125.0,2024.0,1932.0,1890.0,1891.0,1903.0,2038.0
2018-02,1853.0,1842.0,1893.0,1607.0,1947.0,1809.0,1917.0,1910.0,1817.0,1819.0,...,1836.0,1856.0,2026.0,2113.0,2006.0,1932.0,1893.0,1916.0,1899.0,2034.0
2018-03,1846.0,1845.0,1896.0,1575.0,1944.0,1808.0,1925.0,1912.0,1816.0,1825.0,...,1846.0,1855.0,2010.0,2100.0,1989.0,1922.0,1904.0,1914.0,1889.0,2018.0
2018-04,1841.0,1847.0,1898.0,1557.0,1934.0,1804.0,1935.0,1908.0,1814.0,1828.0,...,1849.0,1854.0,1991.0,2086.0,1969.0,1906.0,1920.0,1896.0,1873.0,2006.0
2018-05,1839.0,1849.0,1900.0,1550.0,1925.0,1800.0,1945.0,1907.0,1812.0,1827.0,...,1850.0,1857.0,1977.0,2076.0,1952.0,1890.0,1933.0,1884.0,1861.0,2005.0
2018-06,1837.0,1847.0,1898.0,1547.0,1916.0,1799.0,1946.0,1905.0,1806.0,1825.0,...,1849.0,1857.0,1967.0,2067.0,1935.0,1877.0,1939.0,1876.0,1851.0,2003.0
2018-07,1835.0,1847.0,1898.0,1546.0,1912.0,1799.0,1945.0,1904.0,1802.0,1824.0,...,1849.0,1856.0,1957.0,2056.0,1925.0,1866.0,1940.0,1872.0,1847.0,2005.0

In [10]:
#df = df.dropna(axis=0)

In [11]:
df.index

Index(['2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-07', '2011-08', '2011-09', '2011-10',
       '2011-11', '2011-12', '2012-01', '2012-02', '2012-03', '2012-04',
       '2012-05', '2012-06', '2012-07', '2012-08', '2012-09', '2012-10',
       '2012-11', '2012-12', '2013-01', '2013-02', '2013-03', '2013-04',
       '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10',
       '2013-11', '2013-12', '2014-01', '2014-02', '2014-03', '2014-04',
       '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10',
       '2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04',
       '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10',
       '2015-11', '2015-12', '2016-01', '2016-02', '2016-03', '2016-04',
       '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10',
       '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04',
       '2018-05', '2018-06', '2018-07'],
      dtype='object', name='Date')

In [12]:
df.to_csv("\\Users\\Paul-DS\\Downloads\\Bronx_Rental_Prices_by_BoroDistrict.csv")