In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
#import numpy as np
#import dateutil

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
nyc_rental_load = "\\Users\\Paul-DS\\Downloads\\Neighborhood_Zri_AllHomesPlusMultifamily.csv"
nyc_rental_data=pd.read_csv(nyc_rental_load)
#nyc_mean_price_sales = "Resources/nyc_mean_price_per_sqft.csv"
#nyc_price_per_sqft = pd.read_csv(nyc_mean_price_sales)

In [2]:
brooklyn_rent = nyc_rental_data[nyc_rental_data["CountyName"]=="Kings"]

In [3]:
brooklyn_region=[]
brooklyn_region = brooklyn_rent['RegionName'].unique()

In [4]:
brooklyn_region

array(['East New York', 'Williamsburg', 'Bedford Stuyvesant', 'Flatbush',
       'Crown Heights', 'Bushwick', 'East Flatbush', 'Sunset Park',
       'Borough Park', 'Bensonhurst', 'Canarsie', 'Sheepshead Bay',
       'Gravesend', 'Midwood', 'Flatlands', 'Park Slope', 'Brownsville',
       'Bay Ridge', 'Kensington', 'Bath Beach', 'Coney Island',
       'Ocean Parkway', 'Dyker Heights', 'Fort Greene', 'Greenwood',
       'Greenpoint', 'Prospect Lefferts Gardens', 'Homecrest',
       'Fort Hamilton', 'Brighton Beach', 'Marine Park', 'Clinton Hill',
       'Wingate', 'Gowanus', 'Prospect Heights', 'New Utrecht',
       'Carroll Gardens', 'Boerum Hill', 'Georgetown', 'Downtown',
       'Windsor Terrace', 'Cobble Hill', 'Mill Basin', 'Manhattan Beach',
       'Gerritsen Beach', 'Bergen Beach',
       'Columbia Street Waterfront District', 'DUMBO'], dtype=object)

In [5]:
nyc_region_rent={}
for region in brooklyn_region:
    nyc_region_rent[region] = brooklyn_rent[nyc_rental_data["RegionName"]==region]
    nyc_region_rent[region] = nyc_region_rent[region].drop(columns=["RegionID","RegionName","City","State","Metro","SizeRank","CountyName"]).mean()
    nyc_region_rent[region] = pd.DataFrame(nyc_region_rent[region],columns=[region+' rental price'])

In [6]:
nyc_region_rent[region].index.rename('Date')

Index(['2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-07', '2011-08', '2011-09', '2011-10',
       '2011-11', '2011-12', '2012-01', '2012-02', '2012-03', '2012-04',
       '2012-05', '2012-06', '2012-07', '2012-08', '2012-09', '2012-10',
       '2012-11', '2012-12', '2013-01', '2013-02', '2013-03', '2013-04',
       '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10',
       '2013-11', '2013-12', '2014-01', '2014-02', '2014-03', '2014-04',
       '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10',
       '2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04',
       '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10',
       '2015-11', '2015-12', '2016-01', '2016-02', '2016-03', '2016-04',
       '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10',
       '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04',
       '2018-05', '2018-06', '2018-07'],
      dtype='object', name='Date')

In [7]:
#nyc_region_rent
for region in brooklyn_region:
    nyc_region_rent[region].index.rename('Date',inplace=True)
    #manhattan_region_df = manhattan_region_df.concat(nyc_region_rent[region])
    #manhattan_region_df = manhattan_region_df.join(nyc_region_rent[region])
#nyc_region_rent

In [8]:
first=0
for region in brooklyn_region:
    if first==0:
        df = pd.DataFrame(nyc_region_rent[region])
    else:
        df = df.join(pd.DataFrame(nyc_region_rent[region]))
    first=1

In [9]:
df

,East New York rental price,Williamsburg rental price,Bedford Stuyvesant rental price,Flatbush rental price,Crown Heights rental price,Bushwick rental price,East Flatbush rental price,Sunset Park rental price,Borough Park rental price,Bensonhurst rental price,...,Georgetown rental price,Downtown rental price,Windsor Terrace rental price,Cobble Hill rental price,Mill Basin rental price,Manhattan Beach rental price,Gerritsen Beach rental price,Bergen Beach rental price,Columbia Street Waterfront District rental price,DUMBO rental price
Date,,,,,,,,,,,,,,,,,,,,,
2010-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12,1552.0,2189.0,1680.0,1605.0,1655.0,1672.0,1526.0,1671.0,1675.0,1623.0,...,1625.0,2310.0,1806.0,2146.0,1673.0,1739.0,1545.0,1640.0,2208.0,2671.0
2012-01,1554.0,2192.0,1669.0,1595.0,1649.0,1664.0,1514.0,1665.0,1657.0,1607.0,...,1589.0,2329.0,1803.0,2146.0,1642.0,1695.0,1511.0,1604.0,2229.0,2674.0
2012-02,1555.0,2194.0,1655.0,1591.0,1639.0,1644.0,1504.0,1657.0,1637.0,1596.0,...,1568.0,2358.0,1813.0,2133.0,1625.0,1675.0,1498.0,1586.0,2218.0,2708.0
2012-03,1562.0,2234.0,1651.0,1586.0,1642.0,1634.0,1501.0,1655.0,1627.0,1592.0,...,1555.0,2404.0,1810.0,2145.0,1620.0,1661.0,1504.0,1578.0,2228.0,2756.0
2012-04,1564.0,2283.0,1661.0,1586.0,1641.0,1633.0,1516.0,1662.0,1623.0,1589.0,...,1560.0,2432.0,1805.0,2188.0,1628.0,1661.0,1530.0,1586.0,2265.0,2777.0
2012-05,1592.0,2334.0,1694.0,1586.0,1664.0,1658.0,1542.0,1667.0,1625.0,1597.0,...,1576.0,2455.0,1808.0,2218.0,1653.0,1674.0,1547.0,1603.0,2304.0,2829.0
2012-06,1618.0,2364.0,1731.0,1605.0,1694.0,1693.0,1577.0,1685.0,1646.0,1621.0,...,1606.0,2467.0,1843.0,2246.0,1685.0,1714.0,1566.0,1629.0,2333.0,2909.0
2012-07,1649.0,2395.0,1774.0,1625.0,1735.0,1729.0,1609.0,1703.0,1676.0,1662.0,...,1648.0,2480.0,1878.0,2241.0,1730.0,1774.0,1583.0,1670.0,2322.0,3016.0
2012-08,1662.0,2415.0,1805.0,1651.0,1762.0,1759.0,1626.0,1735.0,1709.0,1697.0,...,1687.0,2499.0,1921.0,2271.0,1779.0,1808.0,1595.0,1715.0,2336.0,3078.0
2012-09,1673.0,2423.0,1830.0,1671.0,1787.0,1784.0,1645.0,1745.0,1720.0,1710.0,...,1720.0,2523.0,1928.0,2293.0,1821.0,1803.0,1611.0,1754.0,2350.0,3157.0
2012-10,1666.0,2440.0,1833.0,1685.0,1796.0,1801.0,1654.0,1751.0,1726.0,1709.0,...,1728.0,2568.0,1940.0,2342.0,1849.0,1769.0,1628.0,1767.0,2393.0,3251.0
2012-11,1662.0,2456.0,1822.0,1701.0,1790.0,1805.0,1671.0,1733.0,1716.0,1693.0,...,1732.0,2614.0,1923.0,2392.0,1850.0,1746.0,1657.0,1774.0,2445.0,3313.0
2012-12,1650.0,2462.0,1808.0,1707.0,1781.0,1800.0,1677.0,1734.0,1710.0,1684.0,...,1722.0,2658.0,1938.0,2459.0,1841.0,1731.0,1666.0,1759.0,2501.0,3325.0
2013-01,1662.0,2468.0,1814.0,1719.0,1777.0,1795.0,1687.0,1722.0,1688.0,1661.0,...,1729.0,2686.0,1957.0,2503.0,1837.0,1724.0,1677.0,1769.0,2533.0,3319.0
2013-02,1670.0,2466.0,1833.0,1719.0,1780.0,1795.0,1695.0,1735.0,1676.0,1640.0,...,1714.0,2718.0,1983.0,2524.0,1822.0,1711.0,1672.0,1751.0,2524.0,3315.0
2013-03,1681.0,2490.0,1857.0,1731.0,1788.0,1804.0,1700.0,1740.0,1680.0,1623.0,...,1720.0,2747.0,1971.0,2533.0,1814.0,1712.0,1685.0,1752.0,2510.0,3281.0
2013-04,1684.0,2493.0,1872.0,1743.0,1803.0,1829.0,1721.0,1758.0,1706.0,1630.0,...,1729.0,2763.0,1957.0,2546.0,1806.0,1720.0,1703.0,1752.0,2524.0,3223.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-02,2223.0,2917.0,2487.0,2113.0,2377.0,2511.0,2001.0,2220.0,2259.0,2175.0,...,2136.0,2938.0,2429.0,2936.0,2325.0,2351.0,2043.0,2239.0,2873.0,3534.0
2016-03,2222.0,2903.0,2478.0,2115.0,2364.0,2500.0,2011.0,2216.0,2253.0,2178.0,...,2143.0,2950.0,2415.0,2919.0,2308.0,2330.0,2051.0,2225.0,2861.0,3545.0
2016-04,2225.0,2885.0,2470.0,2117.0,2358.0,2482.0,2024.0,2206.0,2234.0,2167.0,...,2169.0,2944.0,2404.0,2911.0,2328.0,2352.0,2063.0,2244.0,2867.0,3607.0
2016-05,2229.0,2874.0,2467.0,2134.0,2365.0,2471.0,2058.0,2213.0,2229.0,2158.0,...,2203.0,2933.0,2405.0,2914.0,2359.0,2398.0,2078.0,2275.0,2859.0,3645.0
2016-06,2233.0,2872.0,2469.0,2148.0,2378.0,2469.0,2086.0,2221.0,2231.0,2150.0,...,2235.0,2915.0,2404.0,2915.0,2398.0,2436.0,2091.0,2311.0,2858.0,3670.0
2016-07,2231.0,2879.0,2476.0,2169.0,2395.0,2476.0,2115.0,2244.0,2248.0,2158.0,...,2257.0,2909.0,2408.0,2918.0,2413.0,2464.0,2106.0,2328.0,2855.0,3647.0
2016-08,2231.0,2890.0,2488.0,2186.0,2418.0,2489.0,2146.0,2261.0,2273.0,2182.0,...,2270.0,2904.0,2414.0,2910.0,2428.0,2484.0,2129.0,2338.0,2853.0,3642.0
2016-09,2231.0,2906.0,2496.0,2202.0,2437.0,2500.0,2173.0,2269.0,2292.0,2204.0,...,2281.0,2902.0,2421.0,2896.0,2429.0,2495.0,2150.0,2342.0,2845.0,3638.0
2016-10,2236.0,2923.0,2502.0,2214.0,2452.0,2514.0,2199.0,2269.0,2304.0,2223.0,...,2292.0,2902.0,2427.0,2879.0,2429.0,2497.0,2175.0,2345.0,2834.0,3633.0
2016-11,2241.0,2936.0,2501.0,2219.0,2457.0,2520.0,2214.0,2260.0,2307.0,2231.0,...,2297.0,2902.0,2432.0,2864.0,2428.0,2498.0,2198.0,2346.0,2818.0,3612.0
2016-12,2247.0,2942.0,2496.0,2215.0,2457.0,2514.0,2220.0,2253.0,2308.0,2228.0,...,2295.0,2894.0,2433.0,2845.0,2423.0,2497.0,2223.0,2341.0,2798.0,3599.0
2017-01,2249.0,2939.0,2484.0,2202.0,2450.0,2500.0,2220.0,2248.0,2309.0,2220.0,...,2296.0,2882.0,2429.0,2823.0,2420.0,2494.0,2252.0,2338.0,2769.0,3585.0
2017-02,2249.0,2928.0,2471.0,2183.0,2439.0,2482.0,2220.0,2245.0,2307.0,2215.0,...,2305.0,2862.0,2420.0,2796.0,2414.0,2485.0,2271.0,2341.0,2747.0,3585.0
2017-03,2240.0,2914.0,2456.0,2164.0,2420.0,2460.0,2212.0,2244.0,2305.0,2211.0,...,2308.0,2840.0,2405.0,2770.0,2406.0,2472.0,2274.0,2344.0,2727.0,3606.0
2017-04,2227.0,2913.0,2444.0,2147.0,2390.0,2438.0,2196.0,2241.0,2297.0,2205.0,...,2295.0,2823.0,2387.0,2778.0,2385.0,2465.0,2258.0,2331.0,2724.0,3647.0
2017-05,2211.0,2916.0,2438.0,2138.0,2359.0,2423.0,2180.0,2243.0,2288.0,2200.0,...,2267.0,2831.0,2377.0,2818.0,2358.0,2473.0,2226.0,2309.0,2733.0,3705.0
2017-06,2202.0,2928.0,2441.0,2138.0,2344.0,2427.0,2170.0,2256.0,2283.0,2197.0,...,2246.0,2852.0,2385.0,2868.0,2344.0,2497.0,2195.0,2295.0,2750.0,3748.0
2017-07,2198.0,2940.0,2458.0,2156.0,2357.0,2441.0,2173.0,2273.0,2288.0,2201.0,...,2239.0,2884.0,2413.0,2900.0,2351.0,2521.0,2172.0,2297.0,2764.0,3774.0
2017-08,2207.0,2958.0,2485.0,2186.0,2389.0,2464.0,2183.0,2288.0,2299.0,2209.0,...,2245.0,2916.0,2450.0,2921.0,2369.0,2544.0,2166.0,2310.0,2775.0,3787.0
2017-09,2225.0,2973.0,2517.0,2225.0,2424.0,2488.0,2211.0,2298.0,2315.0,2223.0,...,2262.0,2949.0,2479.0,2937.0,2387.0,2560.0,2179.0,2332.0,2787.0,3788.0
2017-10,2239.0,2968.0,2540.0,2261.0,2450.0,2512.0,2243.0,2307.0,2330.0,2232.0,...,2281.0,2976.0,2499.0,2941.0,2396.0,2569.0,2197.0,2353.0,2794.0,3767.0
2017-11,2235.0,2945.0,2544.0,2288.0,2462.0,2518.0,2267.0,2309.0,2345.0,2224.0,...,2292.0,2981.0,2503.0,2926.0,2405.0,2564.0,2207.0,2371.0,2789.0,3713.0
2017-12,2219.0,2901.0,2526.0,2302.0,2460.0,2500.0,2266.0,2299.0,2347.0,2202.0,...,2288.0,2972.0,2492.0,2904.0,2405.0,2538.0,2202.0,2373.0,2778.0,3643.0
2018-01,2203.0,2853.0,2497.0,2302.0,2446.0,2463.0,2250.0,2277.0,2328.0,2178.0,...,2275.0,2950.0,2470.0,2877.0,2399.0,2501.0,2194.0,2368.0,2765.0,3572.0
2018-02,2195.0,2813.0,2467.0,2289.0,2427.0,2425.0,2232.0,2254.0,2296.0,2158.0,...,2259.0,2930.0,2442.0,2853.0,2380.0,2461.0,2192.0,2355.0,2754.0,3523.0
2018-03,2192.0,2792.0,2443.0,2269.0,2409.0,2393.0,2216.0,2232.0,2261.0,2141.0,...,2245.0,2923.0,2417.0,2840.0,2358.0,2435.0,2193.0,2337.0,2753.0,3488.0
2018-04,2189.0,2776.0,2420.0,2247.0,2393.0,2366.0,2204.0,2213.0,2232.0,2123.0,...,2230.0,2918.0,2394.0,2833.0,2330.0,2415.0,2191.0,2313.0,2750.0,3465.0
2018-05,2185.0,2763.0,2404.0,2231.0,2381.0,2345.0,2196.0,2196.0,2213.0,2108.0,...,2215.0,2918.0,2377.0,2829.0,2308.0,2398.0,2189.0,2290.0,2749.0,3453.0
2018-06,2182.0,2749.0,2392.0,2217.0,2369.0,2327.0,2193.0,2189.0,2201.0,2098.0,...,2204.0,2911.0,2365.0,2824.0,2292.0,2384.0,2186.0,2275.0,2744.0,3445.0
2018-07,2181.0,2740.0,2386.0,2206.0,2359.0,2314.0,2191.0,2185.0,2197.0,2093.0,...,2199.0,2906.0,2356.0,2821.0,2284.0,2374.0,2184.0,2266.0,2741.0,3448.0

In [10]:
#df = df.dropna(axis=0)

In [11]:
df.index

Index(['2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-07', '2011-08', '2011-09', '2011-10',
       '2011-11', '2011-12', '2012-01', '2012-02', '2012-03', '2012-04',
       '2012-05', '2012-06', '2012-07', '2012-08', '2012-09', '2012-10',
       '2012-11', '2012-12', '2013-01', '2013-02', '2013-03', '2013-04',
       '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10',
       '2013-11', '2013-12', '2014-01', '2014-02', '2014-03', '2014-04',
       '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10',
       '2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04',
       '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10',
       '2015-11', '2015-12', '2016-01', '2016-02', '2016-03', '2016-04',
       '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10',
       '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04',
       '2018-05', '2018-06', '2018-07'],
      dtype='object', name='Date')

In [12]:
df.to_csv("\\Users\\Paul-DS\\Downloads\\Brooklyn_Rental_Prices_by_BoroDistrict.csv")