In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
#import numpy as np
#import dateutil

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
nyc_rental_load = "\\Users\\Paul-DS\\Downloads\\Neighborhood_Zri_AllHomesPlusMultifamily.csv"
nyc_rental_data=pd.read_csv(nyc_rental_load)
#nyc_mean_price_sales = "Resources/nyc_mean_price_per_sqft.csv"
#nyc_price_per_sqft = pd.read_csv(nyc_mean_price_sales)

In [2]:
manhattan_rent = nyc_rental_data[nyc_rental_data["CountyName"]=="New York"]

In [3]:
manhattan_rent_mean = manhattan_rent.drop(columns=["RegionID","RegionName","City","State","Metro","SizeRank","CountyName"]).mean()

In [4]:
bronx_rent = nyc_rental_data[nyc_rental_data["CountyName"]=="Bronx"]
bronx_rent_mean = manhattan_rent.drop(columns=["RegionID","RegionName","City","State","Metro","SizeRank","CountyName"]).mean()

In [5]:
queens_rent = nyc_rental_data[nyc_rental_data["CountyName"]=="Queens"]
queens_rent_mean = manhattan_rent.drop(columns=["RegionID","RegionName","City","State","Metro","SizeRank","CountyName"]).mean()

In [6]:
staten_island_rent = nyc_rental_data[nyc_rental_data["CountyName"]=="Richmond"]
staten_island_rent_mean = manhattan_rent.drop(columns=["RegionID","RegionName","City","State","Metro","SizeRank","CountyName"]).mean()

In [7]:
brooklyn_rent = nyc_rental_data[nyc_rental_data["CountyName"]=="Kings"]
brooklyn_rent_mean = manhattan_rent.drop(columns=["RegionID","RegionName","City","State","Metro","SizeRank","CountyName"]).mean()

In [8]:
print(manhattan_rent_mean.head())
print(bronx_rent_mean.head())
print(queens_rent_mean.head())
print(staten_island_rent_mean.head())
print(brooklyn_rent_mean.head())

2010-11   NaN
2010-12   NaN
2011-01   NaN
2011-02   NaN
2011-03   NaN
dtype: float64
2010-11   NaN
2010-12   NaN
2011-01   NaN
2011-02   NaN
2011-03   NaN
dtype: float64
2010-11   NaN
2010-12   NaN
2011-01   NaN
2011-02   NaN
2011-03   NaN
dtype: float64
2010-11   NaN
2010-12   NaN
2011-01   NaN
2011-02   NaN
2011-03   NaN
dtype: float64
2010-11   NaN
2010-12   NaN
2011-01   NaN
2011-02   NaN
2011-03   NaN
dtype: float64

In [9]:
df = pd.DataFrame(manhattan_rent_mean,columns=['Manhattan rental price'])

In [10]:
df = df.join(pd.DataFrame(brooklyn_rent_mean,columns=['Brooklyn rental price']))

In [11]:
df = df.join(pd.DataFrame(bronx_rent_mean,columns=['Bronx rental price']))

In [12]:
df = df.join(pd.DataFrame(queens_rent_mean, columns=['Queens rental price']))

In [13]:
df = df.join(pd.DataFrame(staten_island_rent_mean, columns = ['Staten Island rental price']))

In [14]:
df = df.reset_index(drop=False)

In [15]:
df = df.rename(columns={"index":"Date"})

In [16]:
df

,Date,Manhattan rental price,Brooklyn rental price,Bronx rental price,Queens rental price,Staten Island rental price
0,2010-11,NaN,NaN,NaN,NaN,NaN
1,2010-12,NaN,NaN,NaN,NaN,NaN
2,2011-01,NaN,NaN,NaN,NaN,NaN
3,2011-02,NaN,NaN,NaN,NaN,NaN
4,2011-03,NaN,NaN,NaN,NaN,NaN
5,2011-04,NaN,NaN,NaN,NaN,NaN
6,2011-05,NaN,NaN,NaN,NaN,NaN
7,2011-06,NaN,NaN,NaN,NaN,NaN
8,2011-07,NaN,NaN,NaN,NaN,NaN
9,2011-08,NaN,NaN,NaN,NaN,NaN
10,2011-09,NaN,NaN,NaN,NaN,NaN
11,2011-10,NaN,NaN,NaN,NaN,NaN
12,2011-11,NaN,NaN,NaN,NaN,NaN
13,2011-12,3034.115385,3034.115385,3034.115385,3034.115385,3034.115385
14,2012-01,3016.884615,3016.884615,3016.884615,3016.884615,3016.884615
15,2012-02,3021.461538,3021.461538,3021.461538,3021.461538,3021.461538
16,2012-03,3022.807692,3022.807692,3022.807692,3022.807692,3022.807692
17,2012-04,3040.461538,3040.461538,3040.461538,3040.461538,3040.461538
18,2012-05,3052.846154,3052.846154,3052.846154,3052.846154,3052.846154
19,2012-06,3058.961538,3058.961538,3058.961538,3058.961538,3058.961538
20,2012-07,3069.346154,3069.346154,3069.346154,3069.346154,3069.346154
21,2012-08,3096.076923,3096.076923,3096.076923,3096.076923,3096.076923
22,2012-09,3126.730769,3126.730769,3126.730769,3126.730769,3126.730769
23,2012-10,3139.153846,3139.153846,3139.153846,3139.153846,3139.153846
24,2012-11,3130.961538,3130.961538,3130.961538,3130.961538,3130.961538
25,2012-12,3132.076923,3132.076923,3132.076923,3132.076923,3132.076923
26,2013-01,3123.115385,3123.115385,3123.115385,3123.115385,3123.115385
27,2013-02,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000
28,2013-03,3101.923077,3101.923077,3101.923077,3101.923077,3101.923077
29,2013-04,3120.692308,3120.692308,3120.692308,3120.692308,3120.692308
...,...,...,...,...,...,...
63,2016-02,3777.423077,3777.423077,3777.423077,3777.423077,3777.423077
64,2016-03,3813.076923,3813.076923,3813.076923,3813.076923,3813.076923
65,2016-04,3845.461538,3845.461538,3845.461538,3845.461538,3845.461538
66,2016-05,3848.846154,3848.846154,3848.846154,3848.846154,3848.846154
67,2016-06,3842.576923,3842.576923,3842.576923,3842.576923,3842.576923
68,2016-07,3821.653846,3821.653846,3821.653846,3821.653846,3821.653846
69,2016-08,3793.653846,3793.653846,3793.653846,3793.653846,3793.653846
70,2016-09,3759.153846,3759.153846,3759.153846,3759.153846,3759.153846
71,2016-10,3730.384615,3730.384615,3730.384615,3730.384615,3730.384615
72,2016-11,3703.269231,3703.269231,3703.269231,3703.269231,3703.269231
73,2016-12,3676.423077,3676.423077,3676.423077,3676.423077,3676.423077
74,2017-01,3650.307692,3650.307692,3650.307692,3650.307692,3650.307692
75,2017-02,3627.076923,3627.076923,3627.076923,3627.076923,3627.076923
76,2017-03,3605.076923,3605.076923,3605.076923,3605.076923,3605.076923
77,2017-04,3592.269231,3592.269231,3592.269231,3592.269231,3592.269231
78,2017-05,3597.230769,3597.230769,3597.230769,3597.230769,3597.230769
79,2017-06,3625.653846,3625.653846,3625.653846,3625.653846,3625.653846
80,2017-07,3673.461538,3673.461538,3673.461538,3673.461538,3673.461538
81,2017-08,3716.000000,3716.000000,3716.000000,3716.000000,3716.000000
82,2017-09,3752.269231,3752.269231,3752.269231,3752.269231,3752.269231
83,2017-10,3759.076923,3759.076923,3759.076923,3759.076923,3759.076923
84,2017-11,3744.192308,3744.192308,3744.192308,3744.192308,3744.192308
85,2017-12,3704.538462,3704.538462,3704.538462,3704.538462,3704.538462
86,2018-01,3659.307692,3659.307692,3659.307692,3659.307692,3659.307692
87,2018-02,3618.846154,3618.846154,3618.846154,3618.846154,3618.846154
88,2018-03,3595.076923,3595.076923,3595.076923,3595.076923,3595.076923
89,2018-04,3578.653846,3578.653846,3578.653846,3578.653846,3578.653846
90,2018-05,3566.115385,3566.115385,3566.115385,3566.115385,3566.115385
91,2018-06,3549.923077,3549.923077,3549.923077,3549.923077,3549.923077
92,2018-07,3540.269231,3540.269231,3540.269231,3540.269231,3540.269231

In [20]:
df = df.dropna(axis=0)

In [21]:
df

,Date,Manhattan rental price,Brooklyn rental price,Bronx rental price,Queens rental price,Staten Island rental price
13,2011-12,3034.115385,3034.115385,3034.115385,3034.115385,3034.115385
14,2012-01,3016.884615,3016.884615,3016.884615,3016.884615,3016.884615
15,2012-02,3021.461538,3021.461538,3021.461538,3021.461538,3021.461538
16,2012-03,3022.807692,3022.807692,3022.807692,3022.807692,3022.807692
17,2012-04,3040.461538,3040.461538,3040.461538,3040.461538,3040.461538
18,2012-05,3052.846154,3052.846154,3052.846154,3052.846154,3052.846154
19,2012-06,3058.961538,3058.961538,3058.961538,3058.961538,3058.961538
20,2012-07,3069.346154,3069.346154,3069.346154,3069.346154,3069.346154
21,2012-08,3096.076923,3096.076923,3096.076923,3096.076923,3096.076923
22,2012-09,3126.730769,3126.730769,3126.730769,3126.730769,3126.730769
23,2012-10,3139.153846,3139.153846,3139.153846,3139.153846,3139.153846
24,2012-11,3130.961538,3130.961538,3130.961538,3130.961538,3130.961538
25,2012-12,3132.076923,3132.076923,3132.076923,3132.076923,3132.076923
26,2013-01,3123.115385,3123.115385,3123.115385,3123.115385,3123.115385
27,2013-02,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000
28,2013-03,3101.923077,3101.923077,3101.923077,3101.923077,3101.923077
29,2013-04,3120.692308,3120.692308,3120.692308,3120.692308,3120.692308
30,2013-05,3163.153846,3163.153846,3163.153846,3163.153846,3163.153846
31,2013-06,3202.769231,3202.769231,3202.769231,3202.769231,3202.769231
32,2013-07,3211.923077,3211.923077,3211.923077,3211.923077,3211.923077
33,2013-08,3192.115385,3192.115385,3192.115385,3192.115385,3192.115385
34,2013-09,3203.538462,3203.538462,3203.538462,3203.538462,3203.538462
35,2013-10,3233.692308,3233.692308,3233.692308,3233.692308,3233.692308
36,2013-11,3271.615385,3271.615385,3271.615385,3271.615385,3271.615385
37,2013-12,3296.000000,3296.000000,3296.000000,3296.000000,3296.000000
38,2014-01,3316.038462,3316.038462,3316.038462,3316.038462,3316.038462
39,2014-02,3333.500000,3333.500000,3333.500000,3333.500000,3333.500000
40,2014-03,3326.115385,3326.115385,3326.115385,3326.115385,3326.115385
41,2014-04,3324.115385,3324.115385,3324.115385,3324.115385,3324.115385
42,2014-05,3311.000000,3311.000000,3311.000000,3311.000000,3311.000000
...,...,...,...,...,...,...
63,2016-02,3777.423077,3777.423077,3777.423077,3777.423077,3777.423077
64,2016-03,3813.076923,3813.076923,3813.076923,3813.076923,3813.076923
65,2016-04,3845.461538,3845.461538,3845.461538,3845.461538,3845.461538
66,2016-05,3848.846154,3848.846154,3848.846154,3848.846154,3848.846154
67,2016-06,3842.576923,3842.576923,3842.576923,3842.576923,3842.576923
68,2016-07,3821.653846,3821.653846,3821.653846,3821.653846,3821.653846
69,2016-08,3793.653846,3793.653846,3793.653846,3793.653846,3793.653846
70,2016-09,3759.153846,3759.153846,3759.153846,3759.153846,3759.153846
71,2016-10,3730.384615,3730.384615,3730.384615,3730.384615,3730.384615
72,2016-11,3703.269231,3703.269231,3703.269231,3703.269231,3703.269231
73,2016-12,3676.423077,3676.423077,3676.423077,3676.423077,3676.423077
74,2017-01,3650.307692,3650.307692,3650.307692,3650.307692,3650.307692
75,2017-02,3627.076923,3627.076923,3627.076923,3627.076923,3627.076923
76,2017-03,3605.076923,3605.076923,3605.076923,3605.076923,3605.076923
77,2017-04,3592.269231,3592.269231,3592.269231,3592.269231,3592.269231
78,2017-05,3597.230769,3597.230769,3597.230769,3597.230769,3597.230769
79,2017-06,3625.653846,3625.653846,3625.653846,3625.653846,3625.653846
80,2017-07,3673.461538,3673.461538,3673.461538,3673.461538,3673.461538
81,2017-08,3716.000000,3716.000000,3716.000000,3716.000000,3716.000000
82,2017-09,3752.269231,3752.269231,3752.269231,3752.269231,3752.269231
83,2017-10,3759.076923,3759.076923,3759.076923,3759.076923,3759.076923
84,2017-11,3744.192308,3744.192308,3744.192308,3744.192308,3744.192308
85,2017-12,3704.538462,3704.538462,3704.538462,3704.538462,3704.538462
86,2018-01,3659.307692,3659.307692,3659.307692,3659.307692,3659.307692
87,2018-02,3618.846154,3618.846154,3618.846154,3618.846154,3618.846154
88,2018-03,3595.076923,3595.076923,3595.076923,3595.076923,3595.076923
89,2018-04,3578.653846,3578.653846,3578.653846,3578.653846,3578.653846
90,2018-05,3566.115385,3566.115385,3566.115385,3566.115385,3566.115385
91,2018-06,3549.923077,3549.923077,3549.923077,3549.923077,3549.923077
92,2018-07,3540.269231,3540.269231,3540.269231,3540.269231,3540.269231

In [23]:
df.set_index('Date', inplace=True)

In [24]:
df

,Manhattan rental price,Brooklyn rental price,Bronx rental price,Queens rental price,Staten Island rental price
Date,,,,,
2011-12,3034.115385,3034.115385,3034.115385,3034.115385,3034.115385
2012-01,3016.884615,3016.884615,3016.884615,3016.884615,3016.884615
2012-02,3021.461538,3021.461538,3021.461538,3021.461538,3021.461538
2012-03,3022.807692,3022.807692,3022.807692,3022.807692,3022.807692
2012-04,3040.461538,3040.461538,3040.461538,3040.461538,3040.461538
2012-05,3052.846154,3052.846154,3052.846154,3052.846154,3052.846154
2012-06,3058.961538,3058.961538,3058.961538,3058.961538,3058.961538
2012-07,3069.346154,3069.346154,3069.346154,3069.346154,3069.346154
2012-08,3096.076923,3096.076923,3096.076923,3096.076923,3096.076923
2012-09,3126.730769,3126.730769,3126.730769,3126.730769,3126.730769
2012-10,3139.153846,3139.153846,3139.153846,3139.153846,3139.153846
2012-11,3130.961538,3130.961538,3130.961538,3130.961538,3130.961538
2012-12,3132.076923,3132.076923,3132.076923,3132.076923,3132.076923
2013-01,3123.115385,3123.115385,3123.115385,3123.115385,3123.115385
2013-02,3115.000000,3115.000000,3115.000000,3115.000000,3115.000000
2013-03,3101.923077,3101.923077,3101.923077,3101.923077,3101.923077
2013-04,3120.692308,3120.692308,3120.692308,3120.692308,3120.692308
2013-05,3163.153846,3163.153846,3163.153846,3163.153846,3163.153846
2013-06,3202.769231,3202.769231,3202.769231,3202.769231,3202.769231
2013-07,3211.923077,3211.923077,3211.923077,3211.923077,3211.923077
2013-08,3192.115385,3192.115385,3192.115385,3192.115385,3192.115385
2013-09,3203.538462,3203.538462,3203.538462,3203.538462,3203.538462
2013-10,3233.692308,3233.692308,3233.692308,3233.692308,3233.692308
2013-11,3271.615385,3271.615385,3271.615385,3271.615385,3271.615385
2013-12,3296.000000,3296.000000,3296.000000,3296.000000,3296.000000
2014-01,3316.038462,3316.038462,3316.038462,3316.038462,3316.038462
2014-02,3333.500000,3333.500000,3333.500000,3333.500000,3333.500000
2014-03,3326.115385,3326.115385,3326.115385,3326.115385,3326.115385
2014-04,3324.115385,3324.115385,3324.115385,3324.115385,3324.115385
2014-05,3311.000000,3311.000000,3311.000000,3311.000000,3311.000000
...,...,...,...,...,...
2016-02,3777.423077,3777.423077,3777.423077,3777.423077,3777.423077
2016-03,3813.076923,3813.076923,3813.076923,3813.076923,3813.076923
2016-04,3845.461538,3845.461538,3845.461538,3845.461538,3845.461538
2016-05,3848.846154,3848.846154,3848.846154,3848.846154,3848.846154
2016-06,3842.576923,3842.576923,3842.576923,3842.576923,3842.576923
2016-07,3821.653846,3821.653846,3821.653846,3821.653846,3821.653846
2016-08,3793.653846,3793.653846,3793.653846,3793.653846,3793.653846
2016-09,3759.153846,3759.153846,3759.153846,3759.153846,3759.153846
2016-10,3730.384615,3730.384615,3730.384615,3730.384615,3730.384615
2016-11,3703.269231,3703.269231,3703.269231,3703.269231,3703.269231
2016-12,3676.423077,3676.423077,3676.423077,3676.423077,3676.423077
2017-01,3650.307692,3650.307692,3650.307692,3650.307692,3650.307692
2017-02,3627.076923,3627.076923,3627.076923,3627.076923,3627.076923
2017-03,3605.076923,3605.076923,3605.076923,3605.076923,3605.076923
2017-04,3592.269231,3592.269231,3592.269231,3592.269231,3592.269231
2017-05,3597.230769,3597.230769,3597.230769,3597.230769,3597.230769
2017-06,3625.653846,3625.653846,3625.653846,3625.653846,3625.653846
2017-07,3673.461538,3673.461538,3673.461538,3673.461538,3673.461538
2017-08,3716.000000,3716.000000,3716.000000,3716.000000,3716.000000
2017-09,3752.269231,3752.269231,3752.269231,3752.269231,3752.269231
2017-10,3759.076923,3759.076923,3759.076923,3759.076923,3759.076923
2017-11,3744.192308,3744.192308,3744.192308,3744.192308,3744.192308
2017-12,3704.538462,3704.538462,3704.538462,3704.538462,3704.538462
2018-01,3659.307692,3659.307692,3659.307692,3659.307692,3659.307692
2018-02,3618.846154,3618.846154,3618.846154,3618.846154,3618.846154
2018-03,3595.076923,3595.076923,3595.076923,3595.076923,3595.076923
2018-04,3578.653846,3578.653846,3578.653846,3578.653846,3578.653846
2018-05,3566.115385,3566.115385,3566.115385,3566.115385,3566.115385
2018-06,3549.923077,3549.923077,3549.923077,3549.923077,3549.923077
2018-07,3540.269231,3540.269231,3540.269231,3540.269231,3540.269231

In [25]:
df.index

Index(['2011-12', '2012-01', '2012-02', '2012-03', '2012-04', '2012-05',
       '2012-06', '2012-07', '2012-08', '2012-09', '2012-10', '2012-11',
       '2012-12', '2013-01', '2013-02', '2013-03', '2013-04', '2013-05',
       '2013-06', '2013-07', '2013-08', '2013-09', '2013-10', '2013-11',
       '2013-12', '2014-01', '2014-02', '2014-03', '2014-04', '2014-05',
       '2014-06', '2014-07', '2014-08', '2014-09', '2014-10', '2014-11',
       '2014-12', '2015-01', '2015-02', '2015-03', '2015-04', '2015-05',
       '2015-06', '2015-07', '2015-08', '2015-09', '2015-10', '2015-11',
       '2015-12', '2016-01', '2016-02', '2016-03', '2016-04', '2016-05',
       '2016-06', '2016-07', '2016-08', '2016-09', '2016-10', '2016-11',
       '2016-12', '2017-01', '2017-02', '2017-03', '2017-04', '2017-05',
       '2017-06', '2017-07', '2017-08', '2017-09', '2017-10', '2017-11',
       '2017-12', '2018-01', '2018-02', '2018-03', '2018-04', '2018-05',
       '2018-06', '2018-07'],
      dtype='object', name='Date')

In [26]:
df.to_csv("\\Users\\Paul-DS\\Downloads\\NYC_RENTAL_PRICES_BY_BORO.csv")

In [ ]:
#df.join(pd.DataFrame(nyc_price_per_sqft,column=['Date']))