In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
#import numpy as np
#import dateutil

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
nyc_rental_load = "\\Users\\Paul-DS\\Downloads\\Neighborhood_Zri_AllHomesPlusMultifamily.csv"
nyc_rental_data=pd.read_csv(nyc_rental_load)
#nyc_mean_price_sales = "Resources/nyc_mean_price_per_sqft.csv"
#nyc_price_per_sqft = pd.read_csv(nyc_mean_price_sales)

In [2]:
manhattan_rent = nyc_rental_data[nyc_rental_data["CountyName"]=="New York"]

In [3]:
manhattan_rent_mean = manhattan_rent.drop(columns=["RegionID","City","State","Metro","SizeRank","CountyName"])

In [4]:
manhattan_region=[]
manhattan_region = manhattan_rent_mean['RegionName'].unique()

In [5]:
manhattan_region

array(['Upper West Side', 'Upper East Side', 'Washington Heights',
       'Harlem', 'East Harlem', 'Lower East Side', 'East Village',
       'Gramercy', 'Hamilton Heights', 'Chelsea', 'Greenwich Village',
       'Morningside Heights', 'Financial District', 'Flatiron District',
       'West Village', 'Brooklyn Heights', 'Sutton Place', 'Turtle Bay',
       'Midtown', 'Tudor City', 'Battery Park', 'Roosevelt Island',
       'Murray Hill', 'Little Italy', 'NoHo', 'Garment District'],
      dtype=object)

In [6]:
nyc_region_rent={}
for region in manhattan_region:
    nyc_region_rent[region] = nyc_rental_data[nyc_rental_data["RegionName"]==region]
    nyc_region_rent[region] = nyc_region_rent[region].drop(columns=["RegionID","RegionName","City","State","Metro","SizeRank","CountyName"]).mean()
    nyc_region_rent[region] = pd.DataFrame(nyc_region_rent[region],columns=[region+' rental price'])

In [7]:
nyc_region_rent[region].index.rename('Date')

Index(['2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-07', '2011-08', '2011-09', '2011-10',
       '2011-11', '2011-12', '2012-01', '2012-02', '2012-03', '2012-04',
       '2012-05', '2012-06', '2012-07', '2012-08', '2012-09', '2012-10',
       '2012-11', '2012-12', '2013-01', '2013-02', '2013-03', '2013-04',
       '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10',
       '2013-11', '2013-12', '2014-01', '2014-02', '2014-03', '2014-04',
       '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10',
       '2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04',
       '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10',
       '2015-11', '2015-12', '2016-01', '2016-02', '2016-03', '2016-04',
       '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10',
       '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04',
       '2018-05', '2018-06', '2018-07'],
      dtype='object', name='Date')

In [8]:
#nyc_region_rent
for region in manhattan_region:
    nyc_region_rent[region].index.rename('Date',inplace=True)
    #manhattan_region_df = manhattan_region_df.concat(nyc_region_rent[region])
    #manhattan_region_df = manhattan_region_df.join(nyc_region_rent[region])
#nyc_region_rent

In [9]:
first=0
for region in manhattan_region:
    if first==0:
        df = pd.DataFrame(nyc_region_rent[region])
    else:
        df = df.join(pd.DataFrame(nyc_region_rent[region]))
    first=1

In [10]:
df

,Upper West Side rental price,Upper East Side rental price,Washington Heights rental price,Harlem rental price,East Harlem rental price,Lower East Side rental price,East Village rental price,Gramercy rental price,Hamilton Heights rental price,Chelsea rental price,...,Sutton Place rental price,Turtle Bay rental price,Midtown rental price,Tudor City rental price,Battery Park rental price,Roosevelt Island rental price,Murray Hill rental price,Little Italy rental price,NoHo rental price,Garment District rental price
Date,,,,,,,,,,,,,,,,,,,,,
2010-11,NaN,5971.000000,956.000000,NaN,NaN,NaN,2293.25,NaN,681.0,NaN,...,NaN,NaN,1704.428571,NaN,NaN,NaN,805.000000,1972.0,NaN,NaN
2010-12,NaN,6009.000000,968.500000,NaN,NaN,NaN,2298.00,NaN,687.0,NaN,...,NaN,NaN,1697.857143,NaN,NaN,NaN,808.000000,1950.0,NaN,NaN
2011-01,NaN,6041.000000,986.500000,NaN,NaN,NaN,2296.25,NaN,694.0,NaN,...,NaN,NaN,1695.571429,NaN,NaN,NaN,808.000000,1933.0,NaN,NaN
2011-02,NaN,6066.000000,996.000000,NaN,NaN,NaN,2290.25,NaN,693.0,NaN,...,NaN,NaN,1684.714286,NaN,NaN,NaN,809.000000,1926.0,NaN,NaN
2011-03,NaN,6084.000000,1000.500000,NaN,NaN,NaN,2283.25,NaN,694.0,NaN,...,NaN,NaN,1679.625000,NaN,NaN,NaN,813.000000,1925.0,NaN,NaN
2011-04,NaN,6110.000000,998.500000,NaN,NaN,NaN,2278.00,NaN,695.0,NaN,...,NaN,NaN,1680.125000,NaN,NaN,NaN,819.000000,1932.0,NaN,NaN
2011-05,NaN,6144.000000,996.500000,NaN,NaN,NaN,2277.25,NaN,698.0,NaN,...,NaN,NaN,1689.250000,NaN,NaN,NaN,827.000000,1943.0,NaN,NaN
2011-06,NaN,6180.000000,992.000000,NaN,NaN,NaN,2275.00,NaN,706.0,NaN,...,NaN,NaN,1699.375000,NaN,NaN,NaN,833.000000,1950.0,NaN,NaN
2011-07,NaN,6205.000000,991.500000,NaN,NaN,NaN,2271.25,NaN,716.0,NaN,...,NaN,NaN,1722.500000,NaN,NaN,NaN,839.000000,1956.0,NaN,NaN
2011-08,NaN,6212.000000,986.000000,NaN,NaN,NaN,2266.75,NaN,727.0,NaN,...,NaN,NaN,1738.375000,NaN,NaN,NaN,842.000000,1963.0,NaN,NaN
2011-09,NaN,6224.000000,989.000000,NaN,NaN,NaN,2266.50,NaN,733.0,NaN,...,NaN,NaN,1741.000000,NaN,NaN,NaN,843.000000,1968.0,NaN,NaN
2011-10,NaN,6232.000000,982.000000,NaN,NaN,NaN,2267.50,NaN,735.0,NaN,...,NaN,NaN,1729.000000,NaN,NaN,NaN,841.000000,1970.0,NaN,NaN
2011-11,NaN,6240.000000,981.500000,NaN,NaN,NaN,2267.50,NaN,733.0,NaN,...,NaN,NaN,1716.875000,NaN,NaN,NaN,837.000000,1968.0,NaN,NaN
2011-12,3172.0,4608.500000,1297.333333,2352.0,2549.0,3132.0,2465.40,3111.0,1538.0,3443.0,...,3217.0,3096.0,1887.111111,3135.0,3279.0,2873.0,1872.000000,2782.0,3506.0,3104.0
2012-01,3132.0,4603.000000,1293.333333,2352.0,2530.0,3129.0,2455.60,3086.0,1539.0,3391.0,...,3193.0,3082.0,1869.888889,3096.0,3299.0,2880.0,1866.333333,2774.0,3530.0,3090.0
2012-02,3150.0,4604.000000,1290.000000,2352.0,2502.0,3149.0,2449.60,3093.0,1545.5,3360.0,...,3205.0,3098.0,1858.333333,3118.0,3334.0,2888.0,1872.000000,2766.5,3542.0,3094.0
2012-03,3161.0,4600.000000,1287.666667,2342.0,2465.0,3147.0,2447.40,3088.0,1544.0,3376.0,...,3191.0,3100.0,1845.000000,3127.0,3326.0,2915.0,1870.666667,2763.0,3542.0,3090.0
2012-04,3191.0,3473.666667,1196.250000,2343.0,2442.0,2205.5,2453.20,3117.0,1547.0,3423.0,...,3201.0,3125.0,1656.818182,3165.0,3319.0,2927.0,1880.666667,2771.0,3522.0,3111.0
2012-05,3208.0,3486.333333,1205.750000,2334.0,2453.0,2245.5,2458.60,3137.0,1542.0,3446.0,...,3210.0,3150.0,1668.181818,3178.0,3314.0,2920.0,1888.666667,2780.5,3539.0,3130.0
2012-06,3219.0,3517.666667,1216.250000,2337.0,2463.0,2284.5,2466.60,3160.0,1540.0,3431.0,...,3210.0,3161.0,1687.272727,3195.0,3342.0,2925.0,1897.333333,2779.0,3525.0,3140.0
2012-07,3219.0,3572.333333,1228.250000,2335.0,2473.0,2298.5,2473.40,3166.0,1545.0,3410.0,...,3242.0,3190.0,1706.181818,3215.0,3384.0,2953.0,1903.666667,2780.5,3564.0,3145.0
2012-08,3249.0,3645.333333,1231.000000,2337.0,2490.0,2307.5,2485.20,3207.0,1550.5,3417.0,...,3294.0,3240.0,1720.090909,3260.0,3421.0,3030.0,1923.333333,2784.0,3565.0,3183.0
2012-09,3287.0,3701.000000,1232.000000,2328.0,2523.0,2304.0,2493.20,3246.0,1552.0,3438.0,...,3359.0,3291.0,1732.272727,3296.0,3450.0,3078.0,1939.333333,2803.0,3588.0,3224.0
2012-10,3302.0,3724.666667,1233.000000,2293.0,2529.0,2316.5,2496.40,3261.0,1526.5,3463.0,...,3357.0,3285.0,1738.545455,3303.0,3475.0,3106.0,1948.666667,2822.0,3594.0,3245.0
2012-11,3293.0,3718.000000,1238.500000,2268.0,2513.0,2324.0,2484.40,3241.0,1503.5,3458.0,...,3322.0,3254.0,1740.909091,3278.0,3481.0,3104.0,1949.666667,2821.0,3592.0,3232.0
2012-12,3295.0,3718.666667,1251.000000,2270.0,2498.0,2347.0,2474.00,3232.0,1489.5,3469.0,...,3291.0,3234.0,1736.727273,3271.0,3482.0,3081.0,1953.000000,2812.0,3605.0,3230.0
2013-01,3291.0,3717.666667,1249.500000,2279.0,2486.0,2345.0,2460.40,3236.0,1474.0,3455.0,...,3276.0,3230.0,1729.272727,3260.0,3446.0,3061.0,1957.333333,2790.0,3574.0,3234.0
2013-02,3271.0,3717.333333,1253.500000,2329.0,2519.0,2329.5,2457.00,3219.0,1481.5,3439.0,...,3259.0,3206.0,1725.000000,3238.0,3423.0,3043.0,1949.000000,2779.0,3523.0,3231.0
2013-03,3268.0,3703.666667,1249.500000,2346.0,2537.0,2315.5,2448.80,3206.0,1483.5,3404.0,...,3259.0,3195.0,1729.545455,3217.0,3426.0,3036.0,1951.333333,2762.5,3434.0,3233.0
2013-04,3287.0,3704.333333,1257.250000,2376.0,2565.0,2315.5,2451.60,3220.0,1501.0,3422.0,...,3303.0,3226.0,1739.909091,3244.0,3444.0,3062.0,1961.333333,2783.5,3425.0,3240.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-02,3942.0,4364.000000,1461.250000,2973.0,2966.0,2608.5,3064.20,3735.0,1869.5,4559.0,...,3962.0,3696.0,2120.727273,3732.0,3857.0,3377.0,2273.666667,3433.0,4984.0,3555.0
2016-03,3983.0,4326.000000,1464.500000,2970.0,2954.0,2619.0,3036.40,3754.0,1870.5,4664.0,...,4052.0,3684.0,2117.363636,3745.0,3868.0,3410.0,2276.000000,3481.0,5132.0,3565.0
2016-04,4047.0,4312.333333,1470.250000,2979.0,2958.0,2649.5,3021.20,3779.0,1874.0,4736.0,...,4114.0,3709.0,2115.909091,3764.0,3865.0,3445.0,2285.333333,3504.0,5135.0,3584.0
2016-05,4062.0,4406.000000,1483.500000,3006.0,2980.0,2675.0,3057.20,3793.0,1891.5,4689.0,...,4059.0,3719.0,2121.818182,3791.0,3863.0,3452.0,2301.666667,3517.0,5093.0,3602.0
2016-06,4055.0,4457.333333,1495.250000,3023.0,2999.0,2687.5,3082.60,3800.0,1902.0,4635.0,...,3987.0,3739.0,2130.545455,3793.0,3869.0,3446.0,2310.333333,3529.5,4974.0,3603.0
2016-07,4020.0,4493.666667,1502.750000,3025.0,2998.0,2673.5,3097.60,3791.0,1904.0,4593.0,...,3920.0,3729.0,2139.545455,3785.0,3876.0,3414.0,2315.000000,3528.5,4841.0,3584.0
2016-08,3973.0,4519.666667,1506.000000,3016.0,2986.0,2660.5,3102.60,3773.0,1898.0,4543.0,...,3863.0,3718.0,2146.818182,3758.0,3880.0,3374.0,2311.333333,3509.0,4689.0,3567.0
2016-09,3925.0,4531.666667,1504.000000,3014.0,2981.0,2638.5,3104.00,3743.0,1897.5,4479.0,...,3799.0,3684.0,2144.181818,3721.0,3880.0,3345.0,2303.666667,3485.0,4537.0,3545.0
2016-10,3890.0,4533.333333,1501.500000,3015.0,2985.0,2611.0,3105.60,3713.0,1899.5,4417.0,...,3752.0,3645.0,2135.272727,3682.0,3875.0,3333.0,2293.000000,3465.0,4469.0,3528.0
2016-11,3863.0,4549.333333,1497.750000,3009.0,2987.0,2589.5,3110.20,3683.0,1899.5,4353.0,...,3726.0,3610.0,2120.909091,3650.0,3874.0,3329.0,2281.333333,3436.0,4410.0,3515.0
2016-12,3841.0,4583.666667,1494.750000,2998.0,2981.0,2568.0,3122.40,3655.0,1895.0,4286.0,...,3736.0,3587.0,2104.181818,3620.0,3860.0,3326.0,2268.333333,3390.5,4364.0,3502.0
2017-01,3817.0,4635.666667,1491.500000,2983.0,2968.0,2545.5,3136.00,3623.0,1885.5,4230.0,...,3755.0,3566.0,2085.000000,3591.0,3834.0,3324.0,2255.666667,3339.0,4336.0,3487.0
2017-02,3805.0,4676.666667,1489.000000,2968.0,2953.0,2519.0,3142.60,3597.0,1873.0,4185.0,...,3777.0,3558.0,2069.909091,3563.0,3792.0,3321.0,2247.666667,3299.5,4315.0,3476.0
2017-03,3789.0,4682.666667,1486.000000,2958.0,2945.0,2496.0,3137.20,3574.0,1860.5,4148.0,...,3779.0,3550.0,2061.090909,3540.0,3755.0,3311.0,2243.333333,3278.5,4292.0,3459.0
2017-04,3779.0,4654.666667,1487.500000,2955.0,2943.0,2490.0,3129.60,3566.0,1854.5,4116.0,...,3784.0,3556.0,2060.000000,3533.0,3729.0,3312.0,2244.000000,3273.0,4263.0,3445.0
2017-05,3772.0,4605.333333,1492.750000,2967.0,2955.0,2508.0,3135.40,3578.0,1861.0,4104.0,...,3809.0,3574.0,2070.818182,3550.0,3720.0,3325.0,2249.666667,3277.0,4252.0,3440.0
2017-06,3792.0,4576.000000,1499.750000,2984.0,2972.0,2546.0,3155.40,3615.0,1873.5,4141.0,...,3859.0,3610.0,2090.818182,3585.0,3731.0,3345.0,2261.333333,3294.5,4296.0,3456.0
2017-07,3838.0,4561.666667,1507.750000,3002.0,2992.0,2592.0,3176.00,3669.0,1890.5,4221.0,...,3920.0,3662.0,2117.272727,3653.0,3761.0,3354.0,2279.666667,3326.5,4418.0,3481.0
2017-08,3882.0,4550.000000,1514.000000,3015.0,3006.0,2622.5,3191.60,3713.0,1908.0,4307.0,...,3965.0,3706.0,2138.636364,3712.0,3791.0,3356.0,2298.000000,3366.5,4540.0,3501.0
2017-09,3915.0,4529.333333,1519.250000,3030.0,3017.0,2643.5,3197.00,3754.0,1923.0,4382.0,...,3991.0,3740.0,2152.818182,3765.0,3810.0,3371.0,2311.000000,3411.5,4635.0,3510.0
2017-10,3911.0,4490.666667,1521.500000,3036.0,3025.0,2643.5,3193.40,3765.0,1929.5,4401.0,...,3979.0,3738.0,2157.090909,3775.0,3814.0,3384.0,2308.666667,3435.5,4634.0,3502.0
2017-11,3884.0,4438.000000,1519.000000,3031.0,3026.0,2634.5,3177.60,3760.0,1925.0,4375.0,...,3931.0,3719.0,2152.272727,3759.0,3808.0,3387.0,2293.666667,3436.5,4605.0,3481.0
2017-12,3830.0,4375.000000,1514.500000,3004.0,3011.0,2609.0,3150.60,3729.0,1908.5,4304.0,...,3864.0,3674.0,2139.272727,3713.0,3803.0,3367.0,2272.333333,3413.0,4558.0,3439.0
2018-01,3775.0,4312.000000,1508.250000,2966.0,2981.0,2581.5,3125.80,3691.0,1883.0,4234.0,...,3802.0,3624.0,2125.000000,3655.0,3799.0,3335.0,2252.333333,3381.5,4494.0,3397.0
2018-02,3732.0,4258.000000,1504.250000,2926.0,2941.0,2558.5,3105.40,3653.0,1853.0,4179.0,...,3748.0,3565.0,2117.363636,3608.0,3795.0,3307.0,2238.666667,3354.0,4448.0,3359.0
2018-03,3713.0,4215.000000,1501.000000,2895.0,2908.0,2549.5,3091.40,3642.0,1828.0,4134.0,...,3719.0,3534.0,2122.090909,3603.0,3790.0,3279.0,2238.333333,3323.0,4425.0,3351.0
2018-04,3700.0,4185.666667,1497.750000,2872.0,2881.0,2545.0,3080.20,3646.0,1812.5,4084.0,...,3705.0,3524.0,2134.090909,3618.0,3774.0,3257.0,2247.333333,3292.5,4434.0,3358.0
2018-05,3686.0,4162.666667,1493.750000,2857.0,2860.0,2542.0,3066.60,3655.0,1803.0,4037.0,...,3709.0,3532.0,2152.363636,3639.0,3759.0,3230.0,2261.000000,3263.0,4431.0,3372.0
2018-06,3655.0,4139.333333,1490.750000,2847.0,2845.0,2539.0,3053.60,3651.0,1796.0,3999.0,...,3705.0,3535.0,2174.545455,3647.0,3741.0,3209.0,2269.000000,3241.5,4411.0,3382.0
2018-07,3633.0,4120.000000,1489.000000,2841.0,2837.0,2537.5,3045.20,3645.0,1792.0,3980.0,...,3702.0,3533.0,2197.818182,3655.0,3732.0,3196.0,2274.333333,3230.0,4394.0,3388.0

In [11]:
#df = df.dropna(axis=0)

In [12]:
df.index

Index(['2010-11', '2010-12', '2011-01', '2011-02', '2011-03', '2011-04',
       '2011-05', '2011-06', '2011-07', '2011-08', '2011-09', '2011-10',
       '2011-11', '2011-12', '2012-01', '2012-02', '2012-03', '2012-04',
       '2012-05', '2012-06', '2012-07', '2012-08', '2012-09', '2012-10',
       '2012-11', '2012-12', '2013-01', '2013-02', '2013-03', '2013-04',
       '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10',
       '2013-11', '2013-12', '2014-01', '2014-02', '2014-03', '2014-04',
       '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10',
       '2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04',
       '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10',
       '2015-11', '2015-12', '2016-01', '2016-02', '2016-03', '2016-04',
       '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10',
       '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04',
       '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10',
       '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04',
       '2018-05', '2018-06', '2018-07'],
      dtype='object', name='Date')

In [13]:
df.to_csv("\\Users\\Paul-DS\\Downloads\\NYC_Rental_Prices_by_BoroDistrict.csv")